version = 0.1
[default.deploy.parameters]
stack_name = "bmpproductslambda"
resolve_s3 = true
s3_prefix = "bmpproductslambda"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
